### ISSUE TITLE
ner.embed.pth

### ISSUE THREAD

**Issue by zhuzhikui** [nooralahzadeh/DSNER-pytorch#2]
What's the file: 'ner.embed.pth '.  Is it generated by word2vec. The format of it is not like char + vec

**Comment by nooralahzadeh** [comment]
Hi,
It is created in first run to avoid the time of creating embedding for each words from pre_trained model in next runs. As you can see here :
https://github.com/nooralahzadeh/DSNER-pytorch/blob/d6683dcd245aaeeaeab85653007cbb1088ca113c/src/dsner.py#L249

And yes, it is char+vec !

**Comment by zhuzhikui** [comment]
Wow! Thanks for relying me. I get it. But when I run my dataset some error happen. And when I run part of my data, it works well. The error is as following:
![image](https://user-images.githubusercontent.com/38184263/70129901-8471cc80-16ba-11ea-8e5b-ab6703b0e900.png)

**Comment by nooralahzadeh** [comment]
You'r Welcome. 
Did you do preprocessing? It seems some of the tags in dataset are empty ''!

**Comment by zhuzhikui** [comment]
I'll check it, thank you!

**Comment by nooralahzadeh** [comment]
I am closing this case, since you didn't update me. Please reopen it if you still have a problem with that!
