### ISSUE TITLE
how to  run lstm+crf+sl or lstm+crf

### ISSUE THREAD

**Issue by xidaline** [nooralahzadeh/DSNER-pytorch#3]
if I want to run lstm +crf+sl or lstm +crf  ，how to run it. Whether I only  use ds_fa data, right? Do I need to change other code.

**Comment by nooralahzadeh** [comment]
Please look at the following lines:
https://github.com/nooralahzadeh/DSNER-pytorch/blob/d6683dcd245aaeeaeab85653007cbb1088ca113c/src/dsner.py#L82
`parser.add_argument('--setup', default='H',
                        help="which dataset: H, A+H")`
`parser.add_argument('--mode', default='SL',
                        help="Mode of training: PA+SL,PA ,SL, CRF")`
H: is hand-labeled dataset, A: is distance supervised dataset, and PA is partial annotation learning (PA-CRF) , SL: is selection module. CRF : will be normal CRF.

**Comment by xidaline** [comment]
> Please look at the following lines:
> https://github.com/nooralahzadeh/DSNER-pytorch/blob/d6683dcd245aaeeaeab85653007cbb1088ca113c/src/dsner.py#L82
> 
> 
> `parser.add_argument('--setup', default='H', help="which dataset: H, A+H")`
> `parser.add_argument('--mode', default='SL', help="Mode of training: PA+SL,PA ,SL, CRF")`
> H: is hand-labeled dataset, A: is distance supervised dataset, and PA is partial annotation learning (PA-CRF) , SL: is selection module. CRF : will be normal CRF.

Thanks for your reply.
